const URL='https://hbigfogqrjobawzdbdue.supabase.co',KEY='sb_publishable_LRAkisi90QWpd60uheIFkA_8cZmuACl';
const sb=supabase.createClient(URL,KEY),$=x=>document.getElementById(x);let user=null,profile=null,techProfile=null;
const L={pending:'En attente',accepted:'Acceptée',quoted:'Devis reçu',scheduled:'Planifiée',in_progress:'En cours',completed:'Terminée',rejected:'Refusée',cancelled:'Annulée'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const badge=s=>`<span class="badge ${s==='completed'?'ok':s==='pending'||s==='quoted'?'warn':s==='rejected'||s==='cancelled'?'bad':''}">${L[s]||s}</span>`;
const money=n=>Number(n||0).toLocaleString('fr-FR')+' FCFA';
function modal(v){$('modal')?.classList.toggle('hidden',!v)}
function bindUI(){
 $('authBtn')?.addEventListener('click',()=>modal(true));$('close')?.addEventListener('click',()=>modal(false));$('modal')?.addEventListener('click',e=>{if(e.target===$('modal'))modal(false)});
 $('toSignup')?.addEventListener('click',()=>{$('login').classList.add('hidden');$('signup').classList.remove('hidden')});$('toLogin')?.addEventListener('click',()=>{$('signup').classList.add('hidden');$('login').classList.remove('hidden')});
 $('roleSelect')?.addEventListener('change',e=>$('techFields').classList.toggle('hidden',e.target.value!=='technicien'));
 $('logoutBtn')?.addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});$('dashBtn')?.addEventListener('click',()=>{$('dashboard').classList.remove('hidden');$('dashboard').scrollIntoView({behavior:'smooth'});render()});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindUI);else bindUI();
async function getProfile(u){let {data}=await sb.from('profiles').select('*').eq('id',u.id).maybeSingle();return data||{id:u.id,role:u.user_metadata?.role||'client',first_name:u.user_metadata?.first_name,last_name:u.user_metadata?.last_name,phone:u.user_metadata?.phone}}
async function init(){let {data:{session}}=await sb.auth.getSession();user=session?.user||null;if(user){profile=await getProfile(user);if(profile.role==='technicien'){let r=await sb.from('technicians').select('*').eq('id',user.id).maybeSingle();techProfile=r.data||null}$('authBtn')?.classList.add('hidden');$('userMenu')?.classList.remove('hidden');$('dashboard')?.classList.remove('hidden');$('role').textContent=profile.role==='admin'?'ADMINISTRATION':profile.role==='technicien'?'ESPACE TECHNICIEN':'ESPACE CLIENT';$('welcome').textContent='Bienvenue '+(profile.first_name||'');$('hint').textContent='Vous êtes connecté.';render()}else{$('authBtn')?.classList.remove('hidden');$('userMenu')?.classList.add('hidden')}}
sb.auth.onAuthStateChange(()=>setTimeout(init,0));

$('signupForm').onsubmit=async e=>{e.preventDefault();$('signupMsg').textContent='Création...';const role=$('roleSelect').value;let {data,error}=await sb.auth.signUp({email:$('semail').value.trim(),password:$('spass').value,options:{data:{first_name:$('first').value.trim(),last_name:$('last').value.trim(),phone:$('sphone').value.trim(),role,specialty:role==='technicien'?$('specialty').value:'',service_area:role==='technicien'?$('serviceArea').value.trim():''},emailRedirectTo:location.origin}});if(error)return $('signupMsg').textContent=error.message;if(data.session){await ensureTechProfile(data.user);modal(false)}$('signupMsg').textContent=data.session?'✓ Compte créé':'✓ Vérifiez votre e-mail puis connectez-vous. Les informations technicien seront conservées.'};
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMsg').textContent='Connexion...';let {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('loginMsg').textContent=error?error.message:'✓ Connexion réussie';if(!error)setTimeout(()=>modal(0),300)};
async function ensureTechProfile(u){if(!u)return;const role=u.user_metadata?.role||'client';await sb.from('profiles').upsert({id:u.id,role,first_name:u.user_metadata?.first_name||'',last_name:u.user_metadata?.last_name||'',phone:u.user_metadata?.phone||''});if(role==='technicien')await sb.from('technicians').upsert({id:u.id,specialty:u.user_metadata?.specialty||'',service_area:u.user_metadata?.service_area||'',is_verified:false,is_available:false});}
$('requestForm').onsubmit=async e=>{e.preventDefault();if(!user)return modal(1);$('requestMsg').textContent='Envoi...';let {error}=await sb.from('requests').insert({client_id:user.id,service_type:$('service').value,contact_phone:$('phone').value.trim(),address:$('address').value.trim(),preferred_date:$('date').value?new Date($('date').value).toISOString():null,budget:$('budget').value?Number($('budget').value):null,description:$('description').value.trim(),status:'pending'});$('requestMsg').textContent=error?'Erreur : '+error.message:'✓ Demande envoyée';if(!error){e.target.reset();render()}};
async function render(){if(!user)return;if(profile.role==='technicien')return tech();if(profile.role==='admin')return admin();return client()}
async function client(){let {data:r=[]}=await sb.from('requests').select('*').eq('client_id',user.id).order('created_at',{ascending:false});let ids=r.map(x=>x.id);let {data:q=[]}=ids.length?await sb.from('quotes').select('*').in('request_id',ids).order('created_at',{ascending:false}):{data:[]};let {data:i=[]}=await sb.from('interventions').select('*').eq('client_id',user.id).order('created_at',{ascending:false});$('dashContent').innerHTML=`<div class="grid"><div class="stat"><strong>${r.length}</strong>Demandes</div><div class="stat"><strong>${r.filter(x=>x.status==='pending').length}</strong>En attente</div><div class="stat"><strong>${i.length}</strong>Interventions</div></div><div class="panel"><h3>Mes demandes</h3>${r.length?r.map(x=>{let z=q.find(a=>a.request_id===x.id&&a.status!=='rejected');return `<div class="item"><div class="row"><b>${esc(x.service_type)}</b>${badge(x.status)}</div><p>${esc(x.description)}</p><small>${esc(x.address)}</small>${z?`<div class="item"><div class="row"><b>Devis ${money(z.amount)}</b>${badge(z.status)}</div><p>${esc(z.details||'')}</p>${z.status==='pending'?`<div class="actions"><button class="mini" onclick="acceptQ('${z.id}','${x.id}')">Accepter le devis</button><button class="mini" onclick="rejectQ('${z.id}')">Refuser</button></div>`:''}</div>`:''}</div>`}).join(''):'Aucune demande.'}</div><div class="panel"><h3>Mes interventions</h3>${i.length?i.map(x=>`<div class="item"><div class="row"><b>${L[x.status]||x.status}</b>${money(x.final_amount)}</div><p>${x.scheduled_at?'Rendez-vous : '+new Date(x.scheduled_at).toLocaleString('fr-FR'):''}</p></div>`).join(''):'Aucune intervention.'}</div>`}
async function tech(){let {data:t}=await sb.from('technicians').select('*').eq('id',user.id).maybeSingle();techProfile=t;if(!t)return $('dashContent').innerHTML='<div class="panel"><h3>Profil technicien</h3><p>Votre profil technicien est en attente de création.</p></div>';let {data:a=[]}=await sb.from('requests').select('*').is('technician_id',null).eq('status','pending').order('created_at',{ascending:false});let {data:m=[]}=await sb.from('requests').select('*').eq('technician_id',user.id).order('created_at',{ascending:false});let {data:i=[]}=await sb.from('interventions').select('*').eq('technician_id',user.id).order('created_at',{ascending:false});$('dashContent').innerHTML=`<div class="grid"><div class="stat"><strong>${a.length}</strong>Demandes disponibles</div><div class="stat"><strong>${m.length}</strong>Mes missions</div><div class="stat"><strong>${i.length}</strong>Historique</div></div><div class="panel"><div class="row"><div><h3>Mon profil technicien</h3><p>${esc(t.specialty||'Spécialité non renseignée')} · Zone : ${esc(t.service_area||'Non renseignée')}</p></div><button class="mini ${t.is_available?'primary':''}" onclick="toggleAvailability()">${t.is_available?'🟢 Disponible':'⚪ Indisponible'}</button></div><p>Statut de validation : ${t.is_verified?'✓ Vérifié':'En attente de validation'}</p><div class="actions"><button class="mini" onclick="editTechProfile()">Modifier mon profil</button></div></div><div class="panel"><h3>Demandes disponibles</h3><p class="muted">Les demandes ci-dessous peuvent être prises en charge par vous.</p>${a.length?a.map(x=>`<div class="item"><div class="row"><b>${esc(x.service_type)}</b>${badge(x.status)}</div><p>${esc(x.description)}</p><small>${esc(x.address)} · ${x.preferred_date?'Souhait : '+new Date(x.preferred_date).toLocaleString('fr-FR'):''}</small><div class="actions"><button class="mini primary" onclick="take('${x.id}')">Accepter la mission</button></div></div>`).join(''):'Aucune demande disponible.'}</div><div class="panel"><h3>Mes missions</h3>${m.length?m.map(x=>`<div class="item"><div class="row"><b>${esc(x.service_type)}</b>${badge(x.status)}</div><p>${esc(x.description||'')}</p>${x.status==='accepted'?`<button class="mini" onclick="quote('${x.id}')">Créer un devis</button>`:''}${x.status==='quoted'?'<small>Devis envoyé · En attente du client</small>':''}</div>`).join(''):'Aucune mission acceptée.'}</div><div class="panel"><h3>Historique des interventions</h3>${i.length?i.map(x=>`<div class="item"><div class="row"><b>${L[x.status]||x.status}</b><b>${money(x.final_amount)}</b></div><p>${x.scheduled_at?'Rendez-vous : '+new Date(x.scheduled_at).toLocaleString('fr-FR'):''}</p>${x.status==='scheduled'?`<button class="mini" onclick="setInterventionStatus('${x.id}','in_progress')">Démarrer l'intervention</button>`:''}${x.status==='in_progress'?`<button class="mini primary" onclick="completeIntervention('${x.id}')">Terminer l'intervention</button>`:''}</div>`).join(''):'Aucune intervention.'}</div>`}
async function admin(){let [{data:p=[]},{data:r=[]},{data:t=[]},{data:i=[]}]=await Promise.all([sb.from('profiles').select('*'),sb.from('requests').select('*'),sb.from('technicians').select('*'),sb.from('interventions').select('*')]);$('dashContent').innerHTML=`<div class="grid"><div class="stat"><strong>${p.length}</strong>Utilisateurs</div><div class="stat"><strong>${t.length}</strong>Techniciens</div><div class="stat"><strong>${r.length}</strong>Demandes</div></div><div class="panel"><h3>Demandes récentes</h3>${r.slice(0,15).map(x=>`<div class="item"><div class="row"><b>${esc(x.service_type)}</b>${badge(x.status)}</div><p>${esc(x.description||'')}</p></div>`).join('')||'Aucune demande.'}</div><div class="panel"><h3>Activité</h3><p>${i.length} interventions.</p></div>`}
window.take=async id=>{if(!techProfile?.is_available){alert('Passez votre statut en Disponible avant d’accepter une mission.');return}let {data,error}=await sb.rpc('claim_request',{p_request_id:id});if(error)alert(error.message);else if(!data)alert('Cette demande a déjà été prise par un autre technicien.');render()};
window.quote=async id=>{let a=Number(prompt('Montant du devis en FCFA'));if(!Number.isFinite(a)||a<=0)return;let d=prompt('Détails du devis (matériel, main-d’œuvre, délai...)')||'';let {error}=await sb.from('quotes').insert({request_id:id,technician_id:user.id,amount:a,details:d,status:'pending'});if(!error)await sb.from('requests').update({status:'quoted'}).eq('id',id).eq('technician_id',user.id);alert(error?'Erreur : '+error.message:'Devis envoyé');render()};
window.acceptQ=async(q,r)=>{let {data,error}=await sb.from('quotes').update({status:'accepted',accepted_at:new Date().toISOString()}).eq('id',q).select().single();if(error)return alert(error.message);let {data:req}=await sb.from('requests').select('technician_id').eq('id',r).single();await sb.from('requests').update({status:'scheduled'}).eq('id',r).eq('client_id',user.id);await sb.from('interventions').upsert({request_id:r,client_id:user.id,technician_id:req.technician_id,status:'scheduled',scheduled_at:new Date().toISOString(),final_amount:data.amount},{onConflict:'request_id'});render()};
window.rejectQ=async id=>{await sb.from('quotes').update({status:'rejected'}).eq('id',id);render()};
window.toggleAvailability=async()=>{let next=!techProfile.is_available;let {error}=await sb.from('technicians').update({is_available:next}).eq('id',user.id);if(error)alert(error.message);render()};
window.editTechProfile=async()=>{let specialty=prompt('Spécialité',techProfile.specialty||'');if(specialty===null)return;let area=prompt('Zone d’intervention',techProfile.service_area||'');if(area===null)return;let {error}=await sb.from('technicians').update({specialty,service_area:area}).eq('id',user.id);if(error)alert(error.message);render()};
window.setInterventionStatus=async(id,status)=>{let {error}=await sb.from('interventions').update({status,started_at:status==='in_progress'?new Date().toISOString():null}).eq('id',id).eq('technician_id',user.id);if(error)alert(error.message);render()};
window.completeIntervention=async id=>{let amount=Number(prompt('Montant final en FCFA',techProfile?.last_amount||''));if(!Number.isFinite(amount)||amount<0)return;let {error}=await sb.from('interventions').update({status:'completed',completed_at:new Date().toISOString(),final_amount:amount}).eq('id',id).eq('technician_id',user.id);if(error)alert(error.message);else{let row=await sb.from('interventions').select('request_id').eq('id',id).single();if(row.data)await sb.from('requests').update({status:'completed'}).eq('id',row.data.request_id).eq('technician_id',user.id)}render()};
init();
