const URL='https://hbigfogqrjobawzdbdue.supabase.co';
const KEY='sb_publishable_LRAkisi90QWpd60uheIFkA_8cZmuACl';
const db=window.supabase.createClient(URL,KEY);
const modal=document.getElementById('modal'),login=document.getElementById('login'),signup=document.getElementById('signup');
const open=()=>modal.classList.remove('hidden'),close=()=>modal.classList.add('hidden');
document.getElementById('authBtn').onclick=open;document.getElementById('close').onclick=close;
document.getElementById('signupLink').onclick=()=>{login.classList.add('hidden');signup.classList.remove('hidden')};
document.getElementById('loginLink').onclick=()=>{signup.classList.add('hidden');login.classList.remove('hidden')};
async function refresh(){const {data:{session}}=await db.auth.getSession();const b=document.getElementById('authBtn');if(session){b.textContent='Déconnexion';b.onclick=async()=>{await db.auth.signOut();location.reload()};document.getElementById('hint').textContent='Vous êtes connecté. Votre demande sera enregistrée dans votre espace client.'}else{b.textContent='Connexion';b.onclick=open;document.getElementById('hint').textContent='Connectez-vous pour envoyer une demande sécurisée.'}}
refresh();db.auth.onAuthStateChange(()=>refresh());
document.getElementById('signupForm').onsubmit=async e=>{e.preventDefault();let m=document.getElementById('signupMsg');m.textContent='Création...';const {data,error}=await db.auth.signUp({email:semail.value.trim(),password:spass.value});if(error){m.textContent=error.message;return}if(data.user){const {error:x}=await db.from('profiles').insert({id:data.user.id,first_name:first.value.trim(),last_name:last.value.trim(),phone:sphone.value.trim(),role:'client'});if(x){m.textContent=x.message;return}}m.textContent=data.session?'Compte créé.':'Compte créé. Vérifiez votre e-mail si nécessaire.'};
document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();let m=document.getElementById('loginMsg');const {error}=await db.auth.signInWithPassword({email:email.value.trim(),password:password.value});m.textContent=error?error.message:'Connexion réussie.';if(!error)setTimeout(close,500)};
document.getElementById('requestForm').onsubmit=async e=>{e.preventDefault();let m=document.getElementById('formMsg');const {data:{user}}=await db.auth.getUser();if(!user){m.textContent='Connectez-vous d’abord.';open();return}const payload={client_id:user.id,service_type:service.value,description:description.value.trim(),address:address.value.trim(),preferred_date:date.value?new Date(date.value).toISOString():null,contact_phone:phone.value.trim()};const {error}=await db.from('requests').insert(payload);if(error)m.textContent='Erreur : '+error.message;else{m.textContent='✓ Demande envoyée et enregistrée.';e.target.reset()}};