create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,role text not null default 'client' check(role in('client','technicien','admin')),first_name text,last_name text,phone text,created_at timestamptz default now());
create table if not exists public.technicians(id uuid primary key references public.profiles(id) on delete cascade,specialty text,service_area text,is_verified boolean default false,is_available boolean default false,rating numeric(2,1) default 0,created_at timestamptz default now());
create table if not exists public.requests(id uuid primary key default gen_random_uuid(),client_id uuid not null references public.profiles(id) on delete cascade,technician_id uuid references public.profiles(id) on delete set null,service_type text not null,contact_phone text not null,address text not null,preferred_date timestamptz,budget numeric(12,2),description text not null,status text not null default 'pending',created_at timestamptz default now());
create table if not exists public.quotes(id uuid primary key default gen_random_uuid(),request_id uuid references public.requests(id) on delete cascade,technician_id uuid references public.profiles(id) on delete cascade,amount numeric(12,2) not null,details text,status text default 'pending',accepted_at timestamptz,created_at timestamptz default now());
create table if not exists public.interventions(id uuid primary key default gen_random_uuid(),request_id uuid unique references public.requests(id) on delete cascade,client_id uuid references public.profiles(id) on delete cascade,technician_id uuid references public.profiles(id) on delete cascade,scheduled_at timestamptz,status text default 'scheduled',final_amount numeric(12,2),started_at timestamptz,completed_at timestamptz,created_at timestamptz default now());
create table if not exists public.reviews(id uuid primary key default gen_random_uuid(),intervention_id uuid references public.interventions(id) on delete cascade,client_id uuid references public.profiles(id) on delete cascade,technician_id uuid references public.profiles(id) on delete cascade,rating int check(rating between 1 and 5),comment text,created_at timestamptz default now(),unique(intervention_id,client_id));
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,title text not null,body text not null,read boolean default false,created_at timestamptz default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),intervention_id uuid references public.interventions(id) on delete set null,client_id uuid references public.profiles(id) on delete set null,amount numeric(12,2) not null,method text,status text default 'pending',transaction_ref text,created_at timestamptz default now());
alter table public.technicians add column if not exists is_available boolean default false;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public,pg_catalog as $$
declare r text; begin r=case when new.raw_user_meta_data->>'role'='technicien' then 'technicien' else 'client' end;
insert into public.profiles(id,role,first_name,last_name,phone) values(new.id,r,new.raw_user_meta_data->>'first_name',new.raw_user_meta_data->>'last_name',new.raw_user_meta_data->>'phone') on conflict(id) do update set first_name=excluded.first_name,last_name=excluded.last_name,phone=excluded.phone;
if r='technicien' then insert into public.technicians(id,specialty,service_area,is_available) values(new.id,new.raw_user_meta_data->>'specialty',new.raw_user_meta_data->>'service_area',false) on conflict(id) do update set specialty=excluded.specialty,service_area=excluded.service_area; end if; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public,pg_catalog as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
create or replace function public.is_technician() returns boolean language sql stable security definer set search_path=public,pg_catalog as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='technicien'); $$;
create or replace function public.claim_request(p_request_id uuid) returns boolean language plpgsql security definer set search_path=public,pg_catalog as $$ declare ok boolean; begin if not public.is_technician() then raise exception 'Compte technicien requis'; end if; update public.requests set technician_id=auth.uid(),status='accepted' where id=p_request_id and status='pending' and technician_id is null and exists(select 1 from public.technicians t where t.id=auth.uid() and t.is_available=true); get diagnostics ok = row_count > 0; return ok; end; $$;
revoke all on function public.is_admin() from public;grant execute on function public.is_admin() to authenticated;revoke all on function public.is_technician() from public;grant execute on function public.is_technician() to authenticated;revoke all on function public.claim_request(uuid) from public;grant execute on function public.claim_request(uuid) to authenticated;

alter table public.profiles enable row level security;alter table public.technicians enable row level security;alter table public.requests enable row level security;alter table public.quotes enable row level security;alter table public.interventions enable row level security;alter table public.reviews enable row level security;alter table public.notifications enable row level security;alter table public.payments enable row level security;

drop policy if exists profiles_own on public.profiles;create policy profiles_own on public.profiles for all to authenticated using(id=auth.uid() or public.is_admin()) with check((id=auth.uid() and role in('client','technicien')) or public.is_admin());
drop policy if exists tech_read on public.technicians;create policy tech_read on public.technicians for select to authenticated using(true);
drop policy if exists tech_own on public.technicians;create policy tech_own on public.technicians for insert to authenticated with check(id=auth.uid());
drop policy if exists tech_update on public.technicians;create policy tech_update on public.technicians for update to authenticated using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
drop policy if exists tech_admin on public.technicians;create policy tech_admin on public.technicians for all to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists request_insert on public.requests;create policy request_insert on public.requests for insert to authenticated with check(client_id=auth.uid());
drop policy if exists request_read on public.requests;create policy request_read on public.requests for select to authenticated using(client_id=auth.uid() or technician_id=auth.uid() or (public.is_technician() and status='pending' and technician_id is null) or public.is_admin());
drop policy if exists request_client_update on public.requests;create policy request_client_update on public.requests for update to authenticated using(client_id=auth.uid() or technician_id=auth.uid() or public.is_admin()) with check(client_id=auth.uid() or technician_id=auth.uid() or public.is_admin());

drop policy if exists quote_read on public.quotes;create policy quote_read on public.quotes for select to authenticated using(technician_id=auth.uid() or public.is_admin() or exists(select 1 from public.requests r where r.id=request_id and r.client_id=auth.uid()));
drop policy if exists quote_insert on public.quotes;create policy quote_insert on public.quotes for insert to authenticated with check(technician_id=auth.uid() and exists(select 1 from public.requests r where r.id=request_id and r.technician_id=auth.uid()));
drop policy if exists quote_update on public.quotes;create policy quote_update on public.quotes for update to authenticated using(technician_id=auth.uid() or public.is_admin() or exists(select 1 from public.requests r where r.id=request_id and r.client_id=auth.uid())) with check(technician_id=auth.uid() or public.is_admin() or exists(select 1 from public.requests r where r.id=request_id and r.client_id=auth.uid()));

drop policy if exists intervention_read on public.interventions;create policy intervention_read on public.interventions for select to authenticated using(client_id=auth.uid() or technician_id=auth.uid() or public.is_admin());
drop policy if exists intervention_insert on public.interventions;create policy intervention_insert on public.interventions for insert to authenticated with check(client_id=auth.uid() or technician_id=auth.uid() or public.is_admin());
drop policy if exists intervention_update on public.interventions;create policy intervention_update on public.interventions for update to authenticated using(client_id=auth.uid() or technician_id=auth.uid() or public.is_admin()) with check(client_id=auth.uid() or technician_id=auth.uid() or public.is_admin());
drop policy if exists review_read on public.reviews;create policy review_read on public.reviews for select to authenticated using(client_id=auth.uid() or technician_id=auth.uid() or public.is_admin());
drop policy if exists review_insert on public.reviews;create policy review_insert on public.reviews for insert to authenticated with check(client_id=auth.uid());
drop policy if exists notif_read on public.notifications;create policy notif_read on public.notifications for select to authenticated using(user_id=auth.uid() or public.is_admin());
drop policy if exists pay_read on public.payments;create policy pay_read on public.payments for select to authenticated using(client_id=auth.uid() or public.is_admin());
